const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Solid: 0},
	{suporte: 0},
	{bsu: 0},
	{Flash: 0},
	{bau: 0},
	{Platform: 0},
	{caixa: 0},
	{Porta: 0},
	{Chave: 0},
	{Bomba: 0},
	{ScrollTo: 0},
	{Soldado: 0},
	{Sprite3: 0},
	{SENSOR_SOLIDO: 0},
	{Keyboard: 0},
	{Inimigo_patrulheiro: 0},
	{Direcao: 0},
	{inimigo01: 0},
	{Sensor_inimigo01_direita: 0},
	{Sensor_inimigo01_esquerda: 0},
	{Inimigo02: 0},
	{Canhao: 0},
	{Bala: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Rotate: 0},
	{Municao: 0},
	{Sensor_canhao: 0},
	{VIDA_HUD: 0},
	{ITENS_HUD: 0},
	{Fundo_Preto: 0},
	{Dialago: 0},
	{SpriteFont: 0},
	{Chefao: 0},
	{Audio: 0},
	{Vidas: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	suporte: class extends self.ISpriteInstance {},
	bsu: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Soldado: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	SENSOR_SOLIDO: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Inimigo_patrulheiro: class extends self.ISpriteInstance {},
	inimigo01: class extends self.ISpriteInstance {},
	Sensor_inimigo01_direita: class extends self.ISpriteInstance {},
	Sensor_inimigo01_esquerda: class extends self.ISpriteInstance {},
	Inimigo02: class extends self.ISpriteInstance {},
	Canhao: class extends self.ISpriteInstance {},
	Bala: class extends self.ISpriteInstance {},
	Municao: class extends self.ISpriteInstance {},
	Sensor_canhao: class extends self.ISpriteInstance {},
	VIDA_HUD: class extends self.ISpriteInstance {},
	ITENS_HUD: class extends self.ISpriteInstance {},
	Fundo_Preto: class extends self.ISpriteInstance {},
	Dialago: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Chave: class extends self.ISpriteInstance {},
	Bomba: class extends self.ISpriteInstance {},
	Chefao: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}